### ISSUE TITLE
リアクションの透過をもどす

### ISSUE THREAD

**Issue by Mai-Shinano** [DA-TENSHI/SHINANOSKEY#12]
### 💡 概要

なぜか背景が白
謎すぎる

### 目的

一定の絵文字が見やすくなる

### この機能は自分で実装したいですか？

- [ ] はい、自分で実装してプルリクエストを作成します

**Comment by 1673beta** [comment]
よくわからないのでスクショが欲しい

**Comment by 1673beta** [comment]
![Screenshot_20241114_081120_Vivaldi.jpg](https://github.com/user-attachments/assets/62298c7e-5555-4f00-a7b1-cb2aa97dde3b)

こういうこと？

**Comment by Mai-Shinano** [comment]
それ

**Comment by Mai-Shinano** [comment]
https://github.com/DA-TENSHI/SHINANOSKEY/commit/62c1de2efa5d8569ddb81f4afbf762db5c61c462
たぶんこれかも

**Comment by 1673beta** [comment]
クライアント設定からCSS切り替えられるようにするか

**Comment by 1673beta** [comment]
元PRの意図としては、おそらく一部の絵文字がダークモードで見にくかったりすることがある(:gomenne:とか)から背景追加する、とかだと思われる

**Comment by Mai-Shinano** [comment]
それがよいかも

**Comment by Mai-Shinano** [comment]
これは更新される前のファイルに戻せば直りそう

**Comment by Mai-Shinano** [comment]
✔️
